version: "3.8"

services:
  mysql_db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Saki@1704
      MYSQL_DATABASE: devops_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - devops_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  node_backend:
    build: ./node-backend
    container_name: node_backend
    restart: always
    ports:
      - "5001:5000"
    env_file:
      - ./node-backend/.env
    depends_on:
      mysql_db:
        condition: service_healthy
    networks:
      - devops_network

networks:
  devops_network:

volumes:
  mysql_data:
